selected_lab = [
    'creatinine',
    'BUN',
    'potassium',
    'sodium',
    'calcium',
    'phosphate',
    'chloride',
    'Hgb',
    'Hct',
    'WBC x 1000',
    'ESR',
    'CRP',
    'total protein',
    'albumin',
    'alkaline phos.',
    'ALT (SGPT)',
    'AST (SGOT)',
    'total bilirubin',
    'direct bilirubin',
    'bedside glucose',
    'glucose',
    'anion gap',
    'Vancomycin - trough',
    'Vancomycin - random',
    'Total CO2',
    'paO2',
]

